version: '3'

services:
    php:
        build:
            context: '.'
            args:
                PHP_VERSION: '${DEV_PHP_VERSION}'
        working_dir: /app
        volumes:
            - '.:/app:cached'
        command: 'tail -f /dev/null'
        environment:
            PHP_EXTENSION_PCOV: 1
